#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Nov 29 16:39:17 NPT 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=7
shaderPack=\u00A7aretrovision_v1.70.zip
enableShaders=false
